### ISSUE TITLE
利用docker部署分布式EasyML集群后，平台中的程序和数据集无法下载和查看

### ISSUE THREAD

**Issue by feiruyun** [ICT-BDA/EasyML#105]
在50070界面可对程序和数据集进行下载，但是在登录EML平台后
1. 对程序和数据进行下载时提示错误如下：
![image](https://user-images.githubusercontent.com/12807112/57345389-40970300-717d-11e9-937c-f10ffb8bd310.png)
2. 对数据集进行查看时，提示错误如下：
Loading data failed！
![image](https://user-images.githubusercontent.com/12807112/57345441-68866680-717d-11e9-911f-3684d478e38c.png)

3. 另外在平台网页上 上传数据集和程序时，提示成功，但是在50070界面相应目录下找不到上传的文件，而且在平台网页上对上传的程序和数据集进行下载和查看时，出现和以上同样的错误。

这是什么原因呢？感谢解答！辛苦！ @sinllychen

**Comment by feiruyun** [comment]
ps：
1.在3台电脑上参照https://github.com/ICT-BDA/EasyML/wiki/%E5%88%A9%E7%94%A8docker%E9%83%A8%E7%BD%B2%E5%88%86%E5%B8%83%E5%BC%8FEasyML%E9%9B%86%E7%BE%A4进行部署。
2.start-hadoop和start-oozie都运行成功，/user/root/input下有文件，shell-wf任务状态为SUCCESS。
3.本地hosts文件已添加：
10.10.21.85 hadoop-master hadoop-master.weave.local
10.10.21.85 mysql mysql.weave.local
10.10.21.80 hadoop-slave1 hadoop-slave1.weave.local
10.10.21.86 hadoop-slave2 hadoop-slave2.weave.local

**Comment by sinllychen** [comment]
@feiruyun 您可以去看下hdfs目录下/EML/下是否有数据。 然后通过平台上传数据看下是否成功

**Comment by feiruyun** [comment]
非常感谢！
