### ISSUE TITLE
任务执行结果无法下载

### ISSUE THREAD

**Issue by feiruyun** [ICT-BDA/EasyML#108]
任务执行完成后，点Download下载，提示无法访问。
下载地址如下：
http://10.10.21.85:8080/EasyMLstudio-0.1/EMLStudioMonitor/filedownload?filename=/EML/oozie/APP-PATH-03b9a2cb-4b06-4fed-a474-58ee4da731a2/Columns_Choose-16ad4a7b303-a24d/AA8C6367-C181-45DB-AD0C-D4E906D24D5F
查看结果如下图：
![image](https://user-images.githubusercontent.com/12807112/58095359-6ef8f180-7c05-11e9-9eea-48bf03ef9e92.png)
结果数据显示正常，但是却不能下载。
从上图可以看到，在以下路径中有三个文件：AA8C6367-C181-45DB-AD0C-D4E906D24D5F/AA8C6367-C181-45DB-AD0C-D4E906D24D5F
如果将下载地址手动改为:http://10.10.21.85:8080/EasyMLstudio-0.1/EMLStudioMonitor/filedownload?filename=/EML/oozie/APP-PATH-03b9a2cb-4b06-4fed-a474-58ee4da731a2/Columns_Choose-16ad4a7b303-a24d/AA8C6367-C181-45DB-AD0C-D4E906D24D5F/AA8C6367-C181-45DB-AD0C-D4E906D24D5F/part-00000

就是在之前的下载路径上添加（/AA8C6367-C181-45DB-AD0C-D4E906D24D5F/part-00000）
则可以下载part-00000文件。
请问，如果想一起下载文件夹内的三个文件，该怎么操作？
@sinllychen 谢谢解答！

**Comment by sinllychen** [comment]
@feiruyun 您好，上述截图右上角有个Download ，可以进行下载
