### ISSUE TITLE
关于EasyML平台的几个问题

### ISSUE THREAD

**Issue by feiruyun** [ICT-BDA/EasyML#110]
您好，有几个问题想问一下：
1.版本升级大概什么时间能够完成，可以访问对外链接地址？
2.升级后的版本是否还会开源？
3.如果不开源，是否可以合作？
4.现在的平台前端和后端是松耦合的吗，不改后端的前提下，是不是可以对前端进行二次开发？

非常感谢！

**Comment by sinllychen** [comment]
您好，关于您的问题：
1、目前升级后的版本已经完成，由于版本往产品化方向升级，可能现在不会提供对外链接地址了。
2、升级后的版本目前还没有计划开源
3、合作具体指的是哪方面？
4、开源的这个版本前端和后端不是完全的松耦合，使用的是GWT的MVP模式，可以进行二次开发。

**Comment by sinllychen** [comment]
@feiruyun 您好，关于您的问题：
1、目前升级后的版本已经完成，由于版本往产品化方向升级，可能现在不会提供对外链接地址了。
2、升级后的版本目前还没有计划开源
3、合作具体指的是哪方面？
4、开源的这个版本前端和后端不是完全的松耦合，使用的是GWT的MVP模式，可以进行二次开发。

**Comment by feiruyun** [comment]
@sinllychen 您好，合作方面：
1.现在是否可以购买升级后的版本，如果可以，是否可以提供源码？
2.是否可以定制开发，比如说在现有的版本上新加部分功能？
非常感谢！
