### ISSUE TITLE
环境搭建小问题~

### ISSUE THREAD

**Issue by skytianyu** [ICT-BDA/EasyML#12]
您好，我是一名研一的学生，对您的平台非常感兴趣，但是有些地方没大看明白，就是我这里是Windows系统下，用的是VMware安装了三台虚拟机（centos），hadoop和spark集群已经安装完毕，都能正常运作，我想在我的集群上在使用您的平台，接下来该怎么部署，能不能简单说下，万分感谢！

**Comment by nkzhlee** [comment]
首先你要安装mysql数据库和Oozie并确保能够正常运行，然后在...\src\main\java\server-config.xml这个文件中配置对应的端口和地址，如果配置正确就可以编译测试了~
