### ISSUE TITLE
Where is the DML db scripts for setup?

### ISSUE THREAD

**Issue by ChenShuai1981** [ICT-BDA/EasyML#15]
I can't find DML db scripts in the source, could you tell me where can I find it?

**Comment by sinllychen** [comment]
Hi, we have build mysql docker images and put the db script in the docker image, you can download our docker to build the cluster environment, the detail step you can see [QuickStart.md]( https://github.com/ICT-BDA/EasyML/blob/master/QuickStart.md), about "Preparation for virtual server cluster" chapter.

**Comment by kingchenchina** [comment]
这两个网盘的信息都不存在了吧？为啥不一起放在github中呢？

**Comment by sinllychen** [comment]
@kingchenchina 您好，网盘的信息是永久的连接，您如果当时访问不在，可能是因为我们在更新版本。之所以不放在github中第一个是因为安装包太大了，另一个因为里面包含很多脚本，所以怕和代码弄混了。
