### ISSUE TITLE
数据库表不全，麻烦提供一下谢谢

### ISSUE THREAD

**Issue by dllen** [ICT-BDA/EasyML#17]
Table 'studio.category' doesn't exist

**Comment by sinllychen** [comment]
@dllen I'm sorry, we forget to upload this table script, we wil upload it right now.  Thank you for your reminder.

**Comment by sinllychen** [comment]
@dllen  We have update the [google drive disk](https://drive.google.com/open?id=0B5Lj6qkCMBbFWW5uYlJwb2drb1k)  about mysql scripts，you can download the newest from there.  The [Baidu Cloud](https://pan.baidu.com/s/1bpw72Ir)  will be updated tonight because of the low internet speed.
