### ISSUE TITLE
【重要】关于工程编译平台及开发环境搭建若干说明

### ISSUE THREAD

**Issue by sinllychen** [ICT-BDA/EasyML#18]
Hi，大家好，关于近期有很多用户向我们反馈idea无法运行EML工程的问题以及开发过程中出现较多环境搭建问题，现做出如下几点说明：

**一、关于工程编译环境**

1、`IDEA`版本大家需要下载有GWT插件的或者能够支持GWT插件安装的版本，据反馈`IDEA `Community（社区版）目前不支持GWT插件，我们自己内部测试的版本是ideaIU-15.0.3教育版，该版本自带GWT插件。（注：IDEA环境下的工程打包目前会有一些问题，建议通过Eclipse进行打包）

2、除了`IDEA`编译环境，大家也可以使用`Eclipse`进行EML工程的搭建，当然也是需要保证`Eclipse`已经安装了GWT插件以及Maven的环境。插件的在线安装地址可参考[Eclipse在线安装GWT插件](http://www.gwtproject.org/usingeclipse.html)。 针对Eclipse 4.4 luna版本的GWT插件可[从此下载](https://pan.baidu.com/s/1hsoxNl6)
具体步骤如下：
**a、导入工程。File -> Import -> Import Existing Projects into Workspace**
![1234324](https://user-images.githubusercontent.com/7518364/28445662-78f84c66-6df8-11e7-8dca-348c548d4e3e.png)

**b、Maven clean。右击工程->Run As -> maven clean。**

**c、Maven编译。右击工程->Run As->maven build->goal命令中输入`compile`，同时勾选skip test（一般情况下无需进行test的编译）**
![4ed34799-1f41-473b-ac07-37c5aa2f0ab9](https://user-images.githubusercontent.com/7518364/27325110-f82fc108-55d9-11e7-9514-bf82018307b6.png)

注：若编译失败出现java.tools错误，请将JRE System Library默认的jre7替换为jdk。如下图所示
![qq 20171106102151](https://user-images.githubusercontent.com/7518364/32422633-5b92dd92-c2dc-11e7-83e4-37fa8de5e1cc.png)

**d、GWT编译。右击工程->Run As->maven build->goal命令中输入`gwt:compile`，同时勾选skip test（一般情况下无需进行test的编译）**  该编译会持续较久时间，请耐心等待。

**e、运行工程。右击工程->Run As->Web Application(GWT Super Dev Mode)->选择index.html 即可执行**
![fdsfsd](https://user-images.githubusercontent.com/7518364/27325535-66494ad2-55db-11e7-9b5f-07302c9f372b.png)

**f、执行完之后，系统会在Development Mode下显示本地连接，点击连接即可打开EML主页**
![43](https://user-images.githubusercontent.com/7518364/27325531-62b33748-55db-11e7-8fb3-607834ac7dfd.png)

**g、关于工程打包部署。右击工程->Run As->Maven build-> goal中输入`package`，运行成功之后，会在工程的Target目录下生成对应名字的war包，将war包拷贝到tomcat容器中部署即可**
![12345678](https://user-images.githubusercontent.com/7518364/27386217-af77888a-56c7-11e7-8d25-2adfa81e24aa.png)

注意：在进行打包之前一定要先进行c和d步骤，否则打的包会是开发包而不是编译之后的包。

**二、关于开发环境搭建**

**考虑到大家在使用Docker集群搭建环境出现很多问题，我们近期会在Wiki上发布关于Windows安装EML集群以及Ubuntu安装EML集群的详细说明，敬请大家关注！**

**Comment by AlphaJi** [comment]
果然community版是不行的。。。

**Comment by stefanxinhong** [comment]
在线安装GWT插件的方法已经失效(google),现提供可行的方法http://gwt-plugins.github.io/documentation/index.html

**Comment by stefanxinhong** [comment]
@sinllychen 在windows平台下，进行gwt:compile步骤，出现错误。info信息如下
+

> WARNING] Don't declare gwt-dev as a project dependency. This may introduce complex dependency conflicts
[ERROR] 九月 19, 2017 10:17:01 下午 java.util.prefs.WindowsPreferences <init>
[ERROR] 警告: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[INFO] Loading inherited module 'eml.studio.EMLStudio'
[INFO]    [ERROR] A generator must extend com.google.gwt.core.ext.Generator
[INFO]    [ERROR] Line 27: Unexpected exception while processing element 'generate-with'
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__generate_with_begin(ModuleDefSchema.java:483)
[INFO] 	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO]    [ERROR] Failure while parsing XML
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.util.xml.DefaultSchema.onHandlerException(DefaultSchema.java:58)
[INFO] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
[INFO] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
[INFO] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:240)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
[INFO] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[INFO] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO]    [ERROR] Unexpected error while processing XML
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:371)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
[INFO] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:326)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:246)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:195)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:172)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:144)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:196)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.894 s
[INFO] Finished at: 2017-09-19T22:17:01+08:00
[INFO] Final Memory: 12M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.5.0:compile (default-cli) on project EMLstudio: Command [[
[ERROR] C:\Program Files\Java\jdk1.7.0_80\jre\bin\java -Xmx512m -classpath "D:\KD\EasyML-master\EasyML-master\target\EMLstudio-0.1\WEB-INF\classes;D:\KD\EasyML-master\EasyML-master\src\main\java;D:\KD\EasyML-master\EasyML-master\src\main\resources;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-servlet\2.5.0\gwt-servlet-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-codeserver\2.5.0\gwt-codeserver-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-user\2.5.0\gwt-user-2.5.0.jar;C:\Users\Administrator\.m2\repository\org\json\json\20090211\json-20090211.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-dev\2.5.0\gwt-dev-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-incubator\2.0.1\gwt-incubator-2.0.1.jar;C:\Users\Administrator\.m2\repository\com\allen-sauer\gwt\dnd\gwt-dnd\3.1.2\gwt-dnd-3.1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-common\2.2.0\hadoop-common-2.2.0.jar;C:\Users\Administrator\.m2\repository\com\google\guava\guava\11.0.2\guava-11.0.2.jar;C:\Users\Administrator\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\Administrator\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-math\2.1\commons-math-2.1.jar;C:\Users\Administrator\.m2\repository\xmlenc\xmlenc\0.52\xmlenc-0.52.jar;C:\Users\Administrator\.m2\repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.4\commons-codec-1.4.jar;C:\Users\Administrator\.m2\repository\commons-io\commons-io\2.1\commons-io-2.1.jar;C:\Users\Administrator\.m2\repository\commons-net\commons-net\3.1\commons-net-3.1.jar;C:\Users\Administrator\.m2\repository\javax\servlet\servlet-api\2.5\servlet-api-2.5.jar;C:\Users\Administrator\.m2\repository\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar;C:\Users\Administrator\.m2\repository\org\mortbay\jetty\jetty-util\6.1.26\jetty-util-6.1.26.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-core\1.9\jersey-core-1.9.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-json\1.9\jersey-json-1.9.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jettison\jettison\1.1\jettison-1.1.jar;C:\Users\Administrator\.m2\repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;C:\Users\Administrator\.m2\repository\com\sun\xml\bind\jaxb-impl\2.2.3-1\jaxb-impl-2.2.3-1.jar;C:\Users\Administrator\.m2\repository\javax\xml\bind\jaxb-api\2.2.2\jaxb-api-2.2.2.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-jaxrs\1.8.3\jackson-jaxrs-1.8.3.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-xc\1.8.3\jackson-xc-1.8.3.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-server\1.9\jersey-server-1.9.jar;C:\Users\Administrator\.m2\repository\asm\asm\3.1\asm-3.1.jar;C:\Users\Administrator\.m2\repository\tomcat\jasper-runtime\5.5.23\jasper-runtime-5.5.23.jar;C:\Users\Administrator\.m2\repository\javax\servlet\jsp\jsp-api\2.1\jsp-api-2.1.jar;C:\Users\Administrator\.m2\repository\commons-el\commons-el\1.0\commons-el-1.0.jar;C:\Users\Administrator\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\Administrator\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\repository\net\java\dev\jets3t\jets3t\0.6.1\jets3t-0.6.1.jar;C:\Users\Administrator\.m2\repository\commons-lang\commons-lang\2.5\commons-lang-2.5.jar;C:\Users\Administrator\.m2\repository\commons-configuration\commons-configuration\1.6\commons-configuration-1.6.jar;C:\Users\Administrator\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Administrator\.m2\repository\commons-digester\commons-digester\1.8\commons-digester-1.8.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils-core\1.8.0\commons-beanutils-core-1.8.0.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.5\slf4j-api-1.7.5.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-log4j12\1.7.5\slf4j-log4j12-1.7.5.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.8.8\jackson-core-asl-1.8.8.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.8.8\jackson-mapper-asl-1.8.8.jar;C:\Users\Administrator\.m2\repository\org\apache\avro\avro\1.7.4\avro-1.7.4.jar;C:\Users\Administrator\.m2\repository\com\thoughtworks\paranamer\paranamer\2.3\paranamer-2.3.jar;C:\Users\Administrator\.m2\repository\org\xerial\snappy\snappy-java\1.0.4.1\snappy-java-1.0.4.1.jar;C:\Users\Administrator\.m2\repository\com\google\protobuf\protobuf-java\2.5.0\protobuf-java-2.5.0.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-auth\2.2.0\hadoop-auth-2.2.0.jar;C:\Users\Administrator\.m2\repository\com\jcraft\jsch\0.1.42\jsch-0.1.42.jar;C:\Users\Administrator\.m2\repository\org\apache\zookeeper\zookeeper\3.4.5\zookeeper-3.4.5.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-compress\1.4.1\commons-compress-1.4.1.jar;C:\Users\Administrator\.m2\repository\org\tukaani\xz\1.0\xz-1.0.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-hdfs\2.2.0\hadoop-hdfs-2.2.0.jar;C:\Users\Administrator\.m2\repository\commons-daemon\commons-daemon\1.0.13\commons-daemon-1.0.13.jar;C:\Users\Administrator\.m2\repository\org\apache\hadoop\hadoop-annotations\2.2.0\hadoop-annotations-2.2.0.jar;C:\Users\Administrator\.m2\repository\org\apache\oozie\oozie-client\4.1.0\oozie-client-4.1.0.jar;C:\Users\Administrator\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Administrator\.m2\repository\org\apache\activemq\activemq-client\5.8.0\activemq-client-5.8.0.jar;C:\Users\Administrator\.m2\repository\org\apache\geronimo\specs\geronimo-jms_1.1_spec\1.1.1\geronimo-jms_1.1_spec-1.1.1.jar;C:\Users\Administrator\.m2\repository\org\fusesource\hawtbuf\hawtbuf\1.9\hawtbuf-1.9.jar;C:\Users\Administrator\.m2\repository\org\apache\geronimo\specs\geronimo-j2ee-management_1.1_spec\1.0.1\geronimo-j2ee-management_1.1_spec-1.0.1.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-simple\1.6.6\slf4j-simple-1.6.6.jar;C:\Users\Administrator\.m2\repository\xerces\xercesImpl\2.10.0\xercesImpl-2.10.0.jar;C:\Users\Administrator\.m2\repository\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar;C:\Users\Administrator\.m2\repository\commons-fileupload\commons-fileupload\1.3.2\commons-fileupload-1.3.2.jar;C:\Users\Administrator\.m2\repository\com\sun\mail\javax.mail\1.5.6\javax.mail-1.5.6.jar;C:\Users\Administrator\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\Administrator\.m2\repository\org\apache\ant\ant\1.7.1\ant-1.7.1.jar;C:\Users\Administrator\.m2\repository\org\apache\ant\ant-launcher\1.7.1\ant-launcher-1.7.1.jar;C:\Users\Administrator\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;D:\KD\EasyML-master\EasyML-master\lib\typeparser-1.0.jar;C:\Users\Administrator\.m2\repository\mysql\mysql-connector-java\5.1.26\mysql-connector-java-5.1.26.jar;D:\KD\EasyML-master\EasyML-master\lib\uploader-1.1.0.jar;D:\KD\EasyML-master\EasyML-master\lib\gwt-links-1.3.jar;C:\Program Files\Java\jdk1.7.0_80\lib\tools.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-user\2.5.0\gwt-user-2.5.0.jar;C:\Users\Administrator\.m2\repository\com\google\gwt\gwt-dev\2.5.0\gwt-dev-2.5.0.jar" com.google.gwt.dev.Compiler -logLevel INFO -style OBF -war D:\KD\EasyML-master\EasyML-master\target\EMLstudio-0.1 -localWorkers 8 -XfragmentCount -1 -gen D:\KD\EasyML-master\EasyML-master\target\.generated eml.studio.IndexPage eml.studio.EMLStudio
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sinllychen** [comment]
@stefanxinhong 您在gwt:compile之前 进行maven clean和maven compile都能够成功吗？

**Comment by stefanxinhong** [comment]
是的，都可以成功

2017-09-20 15:46 GMT+08:00 Xinjie Chen <notifications@github.com>:

**Comment by stefanxinhong** [comment]
@sinllychen 是的，都可以成功，gwt:compile也编译了很长时间，似乎快进行完的时候，突然报错。

**Comment by sinllychen** [comment]
@stefanxinhong  你单独右键Google->GWT Compile 看下能成功吗？

**Comment by stefanxinhong** [comment]
@sinllychen 请问，你们使用的eclipse的版本是什么？

**Comment by sinllychen** [comment]
@stefanxinhong  Luna 4.4.0

**Comment by solrex** [comment]
@sinllychen 我的 Eclipse run as 中，没有 Web Application(GWT Super Dev Mode) 选项是什么原因？

![image](https://user-images.githubusercontent.com/1180139/32426783-b76f4644-c2f7-11e7-98ce-116ac7bca3a1.png)

环境如下：

![image](https://user-images.githubusercontent.com/1180139/32426792-c5e326b4-c2f7-11e7-9c5e-818858eae828.png)

![image](https://user-images.githubusercontent.com/1180139/32426802-df1f2f06-c2f7-11e7-8b0c-6ac4b18cb1aa.png)

**Comment by sinllychen** [comment]
@solrex 我觉得应该是版本的问题，我们还没有在新版本的GWT插件上测试过，看起来新版本的GWT插件应该是把一些功能作了一些整合或者移除。我们先在用的是支持Eclipse 4.4(Luna)的GWT插件，具体插件下载地址可[从此下载](https://pan.baidu.com/s/1hsoxNl6)

**Comment by sinllychen** [comment]
关于IDE的工程导入及编译环境说明已添加到[quickstart](https://github.com/ICT-BDA/EasyML/blob/master/QuickStart.md) 中
