### ISSUE TITLE
你就不能搞个中文版的吗？

### ISSUE THREAD

**Issue by better319** [ICT-BDA/EasyML#2]
我郁闷了，还中科院的

**Comment by 599316527** [comment]
你这不正好写个 readme_cn.md PR 一下混个 contributor 嘛

**Comment by hzylmf** [comment]
支持楼上整个readme_cn~^_^

**Comment by nkxujun** [comment]
多谢建议！今天机器之心公众号帮忙给翻译了一下Readme，还挺不错的，http://mp.weixin.qq.com/s/-cerE-TNBWHFVbUvNtJV0g

回头我们也整理一份全的中文文档放上来。
