### ISSUE TITLE
Spark Jar相关的计算jar包没有源码么

### ISSUE THREAD

**Issue by IceMimosa** [ICT-BDA/EasyML#22]

**Comment by nkxujun** [comment]
是指在线Demo中的示例算法吗？目前我们开发的分布式机器学习算法没有开源，只是在系统中进行了演示。现在网上有不少开源机器学习算法包比如Spark下的MLLib等，EasyML系统可以上传并运行这些算法。

**Comment by IceMimosa** [comment]
好的谢谢。
