### ISSUE TITLE
请问在线版本现在怎么访问？

### ISSUE THREAD

**Issue by yandaxin** [ICT-BDA/EasyML#25]
请问现在想访问在线版本去哪个网址，可否提供一个可行账户和密码，因为注册好像用不了。
十分感谢！

**Comment by callmevan** [comment]
目前我们的线上服务正在升级，这导致http://159.226.40.104:18080/dev/ 无法访问。此次升级预计将于下周完成，敬请期待
具体情况可加入微信群访问

**Comment by DataMinder** [comment]
请问微信群怎么加入，谢谢

**Comment by callmevan** [comment]
@DataMinder  在https://github.com/ICT-BDA/EasyML/issues/21 中我们会实时更新微信群的二维码，请关注。
