### ISSUE TITLE
图片显示很乱

### ISSUE THREAD

**Issue by waterlufei** [ICT-BDA/EasyML#26]
我在centos7上面安装docker是可以正常跑起来的，不过我编译代码登录进去后有些图片不能显示，
![image](https://user-images.githubusercontent.com/24197674/29705252-b9a99134-89af-11e7-8640-f2df9a76a65c.png)
这个图片指向这个地址：127.0.0.1:8888/EMLStudio/clear.cache.gif，但是这个地址在源代码里面根本找不到，而且这里主页面登录端口开的8888不是教程上面说的18080

**Comment by sinllychen** [comment]
@waterlufei 您好。您应该是忘记进行gwt编译了。需要使用maven的gwt:compile进行gwt编译之后才能够看到图片
