### ISSUE TITLE
部署成功后，提交自带job报submit failed。

### ISSUE THREAD

**Issue by jimmyyn** [ICT-BDA/EasyML#29]
![11111111111111112](https://user-images.githubusercontent.com/32162339/30690650-7b6a8664-9ef7-11e7-9555-cd74add344f1.png)
![1111111111111](https://user-images.githubusercontent.com/32162339/30690654-7f6055f0-9ef7-11e7-87c0-133d7b7d8179.png)
sh /root/run-wordcount.sh没有问题
系统里面提交job提示submit failed
重装了一次还是不行

**Comment by sinllychen** [comment]
@jimmyyn 您好，请查看一下，您的oozie是否启动正常，具体方法见[QuickStart](https://github.com/ICT-BDA/EasyML/blob/master/QuickStart.md)中的 **Start Oozie service** 部分

**Comment by xfei6868** [comment]
submit后，测试任务样例，只有start ---> End

<workflow-app xmlns="uri:oozie:workflow:0.4" name="Examples of distributed abalone age prediction">
    <start to="end"/>
    <kill name="fail">
        <message>Map/Reduce failed, error message[${wf:errorMessage(wf:lastErrorNode())}]</message>
    </kill>
    <end name="end"/>
</workflow-app>


这个任务生成的貌似不对，请问可能是什么原因？
