### ISSUE TITLE
Does it have an online version?

### ISSUE THREAD

**Issue by jindongwang** [ICT-BDA/EasyML#3]
Very remarkable work it is.
But the real problem is, one has to configure his machine before running this library. It is really burdensome and time-consuming.
Does it have an online version so we can login directly through our browser without even downloading nor configuring? Given the fact that the main interface is web, I believe it is quite doable.
And this could dramatically make EML much more popular.
And plus, the link you provided (http://159.226.40.104:18080/dev/) is not working.

**Comment by nkzhlee** [comment]
Thankyou for your advice. We already have one(http://159.226.40.104:18080/dev/), I am sorry for the website did not work when you were browsing it. You know it is the frist day we release our system, there are numerous users flooded into it. So our system has hung up for  amoment, now it has been recovered.

**Comment by sinllychen** [comment]
Hi, our online system service is being restart at about 9:20 am, maybe you visit just met this action, I am very sorry and now is working.  The configuration about the developing environment is packaged in our [google drive disk](https://drive.google.com/drive/folders/0B5Lj6qkCMBbFWW5uYlJwb2drb1k) and [baidu cloud](http://pan.baidu.com/s/1i5BSiup) , the more detail you can read QuickStart.md .  If you are in windows, You can download a windows docker and execute our build shell script,  it can build your own develop environment easily.

**Comment by rafaelamorim** [comment]
@sinllychen and @nkzhlee
Thanks for your support.
Seems like the google drive folder is outdated... Dockerfile has some bugs and its missing lots of modules that are available in the demo...
I can't access baidu cloud since it's blocked outside china.... It's possible to check this?

Best

**Comment by nkzhlee** [comment]
@rafaelamorim I am sorry for that. You know google drive is not stable in our country, so my latest version had not been uploaded successfully. I have fixed the mistakes now. We appricate that you can connect with us when you get into any trouble. Thx a lot.

**Comment by jindongwang** [comment]
Again the website is not working

**Comment by sinllychen** [comment]
@jindongwang  Is the website not working now?

**Comment by jindongwang** [comment]
@sinllychen I checked many times:
- My PC with Windows 10 under WiFi: not working
- My iPhone with iOS 10 under WiFi: not working
- My iPhone with iOS 10 under 4G: working
- My friend at Xidian Univ. : working
In fact I'm in ICT. So maybe I cannot access the global IP? Please consider about this.

**Comment by nkzhlee** [comment]
@jindongwang  The IP address is available for people who is outside ICT. If you are in ICT, I think you should visit it via a inside [http://10.60.0.50:18080/dev/](address).

**Comment by jindongwang** [comment]
@nkzhlee Finally...
A little suggestion:
It's better to put the both IP directly in the readme.md firstly, instead of downloading and configuration first. I believe most of the people are initially interested and want to have a try. The easy-to-use website will help, while the tedious configuration will hinder the popularity.

**Comment by sinllychen** [comment]
@jindongwang Thank you for your suggestion, we will consider it.

**Comment by AlexG31** [comment]
@sinllychen Is it possible that we can download other program modules online? It seems that the modules provided in Google drive/ Baiduyun only contain LR & GBRT.

**Comment by sinllychen** [comment]
@AlexG31  Yes, you're right.  We only deploy LR&GBRT in this version, you can download other program modules(binary packages) from our online system. But our online system is upgrading this week, you can visit that after this week. Thank you very much!

**Comment by pindegou** [comment]
非计算所IP请访问：http://159.226.40.104:18080/dev/，访问时有特别的要求吗？无法直接访问这个网址，求指导。

**Comment by sinllychen** [comment]
@pindegou 抱歉，我们最近在升级集群，外部地址无法访问，下周应该能够恢复正常。
