### ISSUE TITLE
自己编写的算法包有规范吗？

### ISSUE THREAD

**Issue by tinygg** [ICT-BDA/EasyML#30]
查看了项目的文档和介绍，发现项目里没有提供_用户编写自己的算法包的规范_的描述，能否给一个简单的demo  Job【如下图】，描述一下其中涉及到的算法包的接口规范，能让它们顺利地衔接运行，最好能新建一个example项目。

![123](https://user-images.githubusercontent.com/9475304/30740412-71726d76-9fc3-11e7-8a51-dfa7b81f71a1.png)

**Comment by sinllychen** [comment]
@tinygg 您好，我们在wiki上发布了一个简单的示例，您可以参考一下。https://github.com/ICT-BDA/EasyML/wiki/Simple-Examples-of-EasyML

**Comment by tinygg** [comment]
谢谢，很用心在维护项目！赞一个。
