### ISSUE TITLE
http://159.226.40.104:18080/dev/地址无法访问

### ISSUE THREAD

**Issue by 1066118757** [ICT-BDA/EasyML#31]
您好，感觉您团队开放的工具非常实用，对我们的工作很有帮助。但最近院外的地址总是无法访问。

**Comment by sinllychen** [comment]
@1066118757  您好，前两天我们服务器集群出了一点问题，现已恢复正常。

**Comment by 1066118757** [comment]
目前github上开源的版本和网页上展示的是同一个版本吗？网页版本有些功能在开源安装版本中好像有问题
