### ISSUE TITLE
软件版本的疑问

### ISSUE THREAD

**Issue by 1066118757** [ICT-BDA/EasyML#33]

**Comment by 1066118757** [comment]
目前github上开源的版本和网页上展示的是同一个版本吗？网页版本有些功能在开源安装版本中好像有问题

**Comment by sinllychen** [comment]
@1066118757 不是一个版本。开源的版本是对外服务的版本的简化版本。目前我们也在整合一些新的功能到开源版本中。

**Comment by 1066118757** [comment]
有没有相应的版本区别说明文档之类的介绍？或者不同版本之间的更新信息，不胜感谢

**Comment by sinllychen** [comment]
@1066118757 目前只有开源出来的版本的说明文档。我们正在进行版本的更新，这周应该会发布一个新版本
