### ISSUE TITLE
部署成功后无法访问docker里的容器

### ISSUE THREAD

**Issue by Arjy** [ICT-BDA/EasyML#34]
你好，我已经部署好docker（windows版本）和EML，host也配到了window是的hosts文件中，但是无法在window系统的浏览器访问 http://hadoop-master:50070,http://hadoop-master:18080/EMLStudio 等地址

**Comment by sinllychen** [comment]
@Arjy 你好，你是按照QuickStart中的说明部署的吗？在启动hadoop服务以及oozie服务的时候，有进行验证过吗？

**Comment by Arjy** [comment]
有验证，wordcount例子可以跑，oozie的status为System mode: NORMAL，但是就是没法访问 http://hadoop-master:50070,http://hadoop-master:18080/EMLStudio 等地址

**Comment by Arjy** [comment]
@sinllychen 你好，我有验证，wordcount例子可以跑，oozie的status为System mode: NORMAL，但是就是没法访问 http://hadoop-master:50070,http://hadoop-master:18080/EMLStudio 等地址

**Comment by sinllychen** [comment]
@Arjy 你是用docker toolbox装的吗？

**Comment by Arjy** [comment]
@sinllychen 是的

**Comment by Arjy** [comment]
@sinllychen 不知是哪里的问题，地址如下：
172.18.0.3   hadoop-master
172.18.0.4   hadoop-slave1
172.18.0.5   hadoop-slave2
172.18.0.2      mysql
192.168.99.100 default

**Comment by sinllychen** [comment]
@Arjy 你的host错了。全部都改为192.168.99.100

**Comment by sinllychen** [comment]
@Arjy 文中说的host指的是docker的IP，并不是指的是容器的ip，因为容器的IP是虚拟的IP，实际上在各个端口已经同物理机进行映射过了。所以只需要物理机的IP即docker所在机器的ip。对于docker toolbox来说，就是docker toolbox分给docker的IP

**Comment by Arjy** [comment]
@sinllychen还是不行，我已经把下面这些地址配到window的hosts了，可以telnet hadoop-master 18080，但就是不可以访问http://hadoop-master:18080/EMLStudio
192.168.99.100   hadoop-master
192.168.99.100   hadoop-slave1
192.168.99.100   hadoop-slave2
192.168.99.100     mysql

**Comment by sinllychen** [comment]
@Arjy 麻烦看下你的所有容器都在不在，还有请验证下hadoop：http://hadoop-master:50070/以及oozie：http://hadoop-master:11000/oozie/页面是否访问正常。

**Comment by Arjy** [comment]
@sinllychen 你好，容器hadoop-master，mysql，hadoop-slave1， hadoop-slave2 都在oozie 的状态也是System mode: NORMAL ，界面就是都不可以访问hadoop：http://hadoop-master:50070/ 以及
oozie：http://hadoop-master:11000/oozie/

**Comment by sinllychen** [comment]
@Arjy 你的hadoop主页以及oozie主页访问不了表示hadoop以及oozie应该还是有问题，你替换一下hadoop-master 为192.168.99.100  用地址访问看看。如果用地址访问也不行。很有可能是安装过程中出错了。麻烦您重新安装，然后排查下问题。

**Comment by Arjy** [comment]
@sinllychen  我试过执行tomcat容器时，也没法访问web，然后重装DockerToolbox ，重装EML，执行sh build_network.sh这一步时会报这种错 Error response from daemon: network with name shadownet already exists。最后我总是觉得是不是我电脑系统跟dockerToolbox之间的问题，问题真揪心还没法解决，真不好意思，已经麻烦你很多了，

**Comment by sinllychen** [comment]
@Arjy build_network.sh这一个步骤，只要运行一次即可。你之前运行过了，不需要再运行了。你参照一下这篇文章重新走一遍流程看下有什么问题吧。https://github.com/ICT-BDA/EasyML/wiki/Docker-Toolbox-%E6%90%AD%E5%BB%BAEasyML-%E9%9B%86%E7%BE%A4

**Comment by Arjy** [comment]
你好，刚才我配置virtual box的端口转发，将我电脑的127.0.0.1的端口跟docker的做了映射，就行了，麻烦你太多了，今天继续学习你们的东西，不懂的还要再麻烦你们，太谢谢你了

**Comment by Arjy** [comment]
@sinllychen 早上好，刚才我配置virtual box的端口转发，将我电脑的127.0.0.1的端口跟docker的做了映射，就行了，麻烦你太多了，今天继续学习你们的东西，不懂的还要再麻烦你们，太谢谢你了
