### ISSUE TITLE
demo版本与对外github上发布的是否一致？有哪些区别？

### ISSUE THREAD

**Issue by ali8zake** [ICT-BDA/EasyML#36]
我并没有走docker拉取镜像，只是mvn package 后部署了war包
对比了下界面，发现少不少东西，是少了什么步骤吗？
另外我看跑oozie里，应该有个spark.jar,这个是在镜像里才有？源码部分目前没有放出？
这个操作栏也没看到
![image](https://user-images.githubusercontent.com/761040/31498741-72c35fcc-af28-11e7-9919-0c69340fe117.png)

![image](https://user-images.githubusercontent.com/761040/31498702-4ec6fd4a-af28-11e7-89cb-99cd7712470e.png)
![image](https://user-images.githubusercontent.com/761040/31498709-59114652-af28-11e7-8f03-6eac80f62f66.png)
谢谢！

**Comment by sinllychen** [comment]
@ali8zake 您指的github上发布的是我们对外的服务吗？我们对外的那个服务网址里面的工程并不是我们github这边开源的。有部分功能目前是没有开源的。github中开源的项目与wiki中的文档以及quickstart中的界面是一致的。

**Comment by ali8zake** [comment]
好的，我明白了。

**Comment by yizt** [comment]
@sinllychen 您好， spark.jar的源码可以给一份么？

**Comment by sinllychen** [comment]
@yizt 抱歉，目前我们算法的源码没有开源，暂时不能对外展示，关于相关使用，您可以查看API文档或对外系统中的相关示例。
![123](https://user-images.githubusercontent.com/7518364/33157508-82bf1ac0-d03d-11e7-8cc0-ad2a79fcec2e.png)

**Comment by yizt** [comment]
@sinllychen 请问api文档在哪里？有链接没？您发的只是一张图片

**Comment by sinllychen** [comment]
@yizt 您好，是 http://159.226.40.104:18080/dev/ 首页的API DOC

**Comment by yizt** [comment]
@sinllychen   http://159.226.40.104:18080/dev/无法访问，159.226.40.104  ping 不通
