### ISSUE TITLE
系统安全问题

### ISSUE THREAD

**Issue by 1066118757** [ICT-BDA/EasyML#38]
老师您好，您的平台使我们大数据处理数据分析的一个方便快捷可视化工具。
但是我有一个问题，平台能够直接上传程序和算法，甚至可以直接向服务器上传Shell脚本。
怎样保证系统的安全和稳定性是如何保证的，如何避免异常脚本文件对系统可能造成的不利影响

**Comment by sinllychen** [comment]
@1066118757 您好，目前我们对系统的安全性做的比较少，因为我们课题组不太擅长这方面的研究，您提到的上述问题我们目前正在考虑，会在后续的版本发布中解决这个问题。也欢迎您和我们一起讨论

**Comment by sinllychen** [comment]
@1066118757 抱歉这个问题比较敏感，之前回复的就不保留啦
