### ISSUE TITLE
move Dockerfile to github

### ISSUE THREAD

**Issue by xuxinkun** [ICT-BDA/EasyML#4]
> Thus we need to download the Dockerfile and all dependent files and configuration files from our google drive disk or Baidu Cloud.

I have checked the files in the google drive disk. And I found there are many tars of open source projects. Are they official tars? Or have easyml customed some of them? If they are official tars, why not just add the download link in Dockerfile?

BTW, I think it is a good way to put the files and configuration into github. Maybe the community can make some suggestions about building and deploying.

**Comment by nkzhlee** [comment]
I am in charge of the docker part. Frist, their are not completely official tars, in which I have done  numerous changes. 
And the second question, the tars are too large to upload to github. So thank you for your advice, good luck~

**Comment by xuxinkun** [comment]
@nkzhlee  Actually, I have found some mistakes in the script. I suggest that the scripts and configs other than tars should be uploaded to github. So that we could do some help to improve it. 
And also I recommend `compose` to manage the containers instead of scripts.

**Comment by nkzhlee** [comment]
@xuxinkun It will be great if you can show me the mistakes and join us to improve this project. We can have some communications about it, you can send me an email(nkzhaohuilee@gmail.com). 
And about the github thing, the docker environment is an developer tool to run the EMLStudio. and so we did not upload it to github in case people mix them up.

**Comment by xuxinkun** [comment]
@nkzhlee  I found that the files in google drive disk are not same as in Baidu Cloud. I make use of the Dockerfile of  google drive disk and found some mistake. And then I also unzip the Dockerfile of Baidu Cloud. The mistake such as `FROM ubuntu_eml ` ,`mv /tmp/BDAStudio.war /usr/local/apache-tomcat-8.5.11/webapps ` has been fixed. 
But now I faced a new problem. In `run_containers.sh`, the 3th line is
```
docker run --name mysql --net shadownet --ip 172.18.0.2 --hostname mysql -p 3306:3306 -d nkxujun/emlsql
```
But `nkxujun/emlsql` image does not exist. I guess it should be `nkxujun/mysql_eml`, yes?

**Comment by nkzhlee** [comment]
@xuxinkun You are right. It is nkxujun/mysql_eml. You know google drive is not stable in our country, so my latest version had not been upload success. I have fixed the mistakes now.  we appricate that you can connect with us when you get into any trouble. Thx a lot.
