### ISSUE TITLE
运行 index.html 报错：Unknown argument: -superDevMode

### ISSUE THREAD

**Issue by solrex** [ICT-BDA/EasyML#40]
开发者你好，

我使用 Eclipse 编译 EasyML 是成功的，但是用 gwt 运行报错，错误如下：

```
Unknown argument: -superDevMode
Google Web Toolkit 2.5.0
DevMode [-noserver] [-port port-number | "auto"] [-whitelist whitelist-string] [-blacklist
 blacklist-string] [-logdir directory] [-logLevel level] [-gen dir] [-bindAddress
host-name-or-address] [-codeServerPort port-number | "auto"] [-server
servletContainerLauncher[:args]] [-startupUrl url] [-war dir] [-deploy dir] 
[-extra dir] [-workDir dir] module[s] 

where 
  -noserver        Prevents the embedded web server from running
  ......
  module[s]        Specifies the name(s) of the module(s) to host
```

我的环境是：

Eclipse IDE for C/C++ Developers

Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

然后从 Eclipse 市场下载的：
GWT Eclipse Plugin 3.0.0.201710131939
Eclipse.org - m2e 1.8.2.20171007-0217

Index Page 的 Run Configuration 是这样的：

![image](https://user-images.githubusercontent.com/1180139/32361503-ff628208-c09b-11e7-8da7-1a1d81f2649e.png)

![image](https://user-images.githubusercontent.com/1180139/32361510-16cf829c-c09c-11e7-8be5-c7080e8e29cf.png)

不知道此问题该如何解决，多谢！

谢谢！

**Comment by sinllychen** [comment]
@solrex 您好，EasyML是一个Java Web项目，应该不能使用Eclipse for C++/C Developers编译器。请下载Eclipse JAVA EE IDE For Web Developers。

**Comment by solrex** [comment]
@sinllychen Eclipse 理论上可以编译任意语言啊，而且实时上我都编译成功了，只是运行失败。不过我试下你的建议吧。

**Comment by solrex** [comment]
@sinllychen 使用 Jave EE 的 IDE 也不对。恕我直言，我感觉 EasyML 的 gwt 编译依赖没有搞对，比如编译的时候，有以下问题：
[INFO] --- gwt-maven-plugin:2.5.0:compile (default-cli) @ EMLstudio ---
[WARNING] Don't declare gwt-dev as a project dependency. This may introduce complex dependency conflicts

上面的错误提示 Unknown argument: -superDevMode
Google Web Toolkit 2.5.0
我觉得是项目 pom.xml 中依赖的 gwt 2.5 根本不支持 -superDevMode，而用户却改不了这个依赖。

请问在哪里能招到一份完整地，使用一个 Clean Eclipse Enveriment 构建并运行 EasyML 的教程？我 step by step 地去做，看看还有没有问题？

**Comment by sinllychen** [comment]
@solrex 您好，EasyML的配置，我们内部测试过很多遍，没有遇到您上述出现的问题，Eclipse JaveEE 环境请参考一下https://github.com/ICT-BDA/EasyML/issues/18， IDEA环境请参考quickstart

**Comment by weiwenying** [comment]
我也遇到同样的问题，提示Unknown argument: -superDevMode

请问这个问题是否已经解决？

eclipse 版本：eclipse-jee-photon-R-linux-gtk-x86_64
Google Web Toolkit 2.5.0
