### ISSUE TITLE
Google Drive上的环境无法构建，缺少文件

### ISSUE THREAD

**Issue by qiwihui** [ICT-BDA/EasyML#49]
使用从 google drive 上下载的文件进行build时，出现如下错误

```sh
mv: cannot stat '/tmp/EMLStudio.war': No such file or directory
```

研究发现文件夹中缺少一些构建需要的文件，google drive 上的文件需要更新到最新，谢谢!

**Comment by rh01** [comment]
参考 https://github.com/ICT-BDA/EasyML/issues/10

**Comment by sinllychen** [comment]
@qiwihui google网盘上的EMLStudio.war文件已经重新上传，之前因为网络不稳定，上传没有成功。
