### ISSUE TITLE
如何本地部署或二次开发分布式EML？

### ISSUE THREAD

**Issue by Blusea** [ICT-BDA/EasyML#5]
如何本地部署或二次开发分布式EML？

**Comment by nkzhlee** [comment]
You can refer to  [https://github.com/ICT-BDA/EasyML/blob/master/QuickStart.md](QucikStart) especially the chapter #Preparation for virtual server cluster. Good luck~

**Comment by lanmeipeilizhi** [comment]
请问如何使用？连接打不开

**Comment by nkzhlee** [comment]
@Blusea 可以复制链接地址到你的浏览器，或者仔细阅读readme~
