### ISSUE TITLE
启动耗时问题

### ISSUE THREAD

**Issue by bbbxxxbx** [ICT-BDA/EasyML#57]
将EasyML部署到集群上进行测试时发现，oozie通过map-reduce的map启动程序的耗时特别长，平均达到15秒，请问你们也有相似的问题吗？因为我在集群上和在线的版本上分别跑了相同的简单计算的任务，发现时间差别很大额。

**Comment by sinllychen** [comment]
@bbbxxxbx 这个时间和你的服务器CPU及内存，以及网络的通信情况有关系。docker部署也会相对于集群部署会耗时一些，但是不至于您说的差那么多。

**Comment by bbbxxxbx** [comment]
非常感谢您的答复。我这边是通过CDH在三台服务器上部署集群的。我想问一下这个耗时会受到一些设置参数或策略影响吗？还是仅仅和您说的硬件因素相关呢？

**Comment by sinllychen** [comment]
@bbbxxxbx  主要是取决于您服务器的硬件以及您和您的服务器所在的网络速度。您可以测试一下单独在oozie上提交一个任务的时间大概是多少，就不通过EasyML提交。

**Comment by bbbxxxbx** [comment]
这个测试过了，启动耗时一样的漫长啊。所以就想问是不是配置啥的有问题。。
