### ISSUE TITLE
系统是否支持独立部署的Hadoop集群

### ISSUE THREAD

**Issue by jxzkin** [ICT-BDA/EasyML#59]
EeasyML是否支持对接现存独立部署的Hadoop集群资源，感谢~

**Comment by sinllychen** [comment]
@jxzkin 您好，支持的，只要您自己部署hadoop集群、oozie、然后导入我们的数据库以及数据就可以运行。具体您可以参照我们的docker部署包里面的脚本。其实对于docker来说，里面就是单独部署的集群。只是我们将这个过程自动化了，不需要用户一步一步进行搭建环境
