### ISSUE TITLE
是否支持第三方库的动态接入？

### ISSUE THREAD

**Issue by lijiansong** [ICT-BDA/EasyML#6]
直接用中文吧，整个系统实现起来还是有点工程量的，不知道这个系统是否支持第三方库的动态接入？如果你们能够实现第三方库的动态导入就会更加吸引人了。我的意思是，你们在这个系统上添加一个`接口描述层`，第三方的机器学习库如果想接入你们的系统，只需要提供一个接口描述文件，就可以`动态地生成这个第三方库的可视化拖拽单元`，这样的话整个系统可能会更加cool一点，更加新引人了

**Comment by sinllychen** [comment]
Hi，不太明白您说的第三方动态库导入指的是什么？我们现在支持自己写的算法包通过程序的形式上传、或者对于第三方的lib库，通过maven 引入的方式可以引用到工程中。您指的是那种类似于数据接入的方式吗？比如调用接口服务之类的方式调用第三方库？

**Comment by lijiansong** [comment]
@sinllychen 不好意思，我没有仔细地看这个系统，我的意思是，第三方的接口服务能否动态地集成到这个系统里面，不是通过重新编译整个工程的方式，而是通过第三方的接口开发者提供一个接口描述文件，就可以自动地生成这个库的可视化单元。是否支持这个功能？

**Comment by sinllychen** [comment]
@lijiansong 我理解您的意思了，您的意思是说系统提供第三方接口的调用描述，包括参数，输入输出等，然后系统自动根据这些信息生成对应的算法组件即系统中program，用户直接进行调用即可。您这个提议挺好的，目前我们系统还没有这个功能，后续会考虑加入这个功能。多谢建议！

**Comment by lijiansong** [comment]
@sinllychen 是的，就是这个意思，你们已经做的很不错了。机器之心的介绍，你们面向的用户只是算法的实现者，要是能把第三方接口的开发商也囊括进来就更加通用了

**Comment by sinllychen** [comment]
我们系统支持用户自己上传程序，用户提供程序包（第三方或自己写的程序包），然后配置调用程序包中某个接口的相关参数和输入输出，系统自动生成program组件，和您说的类似。不过这些配置参数是用户自己配置的，不是自动识别接口然后生成的。
