### ISSUE TITLE
是否支持Tensorflow、Torch？

### ISSUE THREAD

**Issue by baitian77** [ICT-BDA/EasyML#62]
是否会支持Tensorflow、Tensorflow-Serving？

**Comment by sinllychen** [comment]
@baitian77 您好，最新发布的1.2.0版本已经支持tensorflow单机和分布式。目前不支持Tensorflow-Serving以及Torch。具体部署可参考我们quickstart.md，具体的tensorflow模型说明可参考https://github.com/ICT-BDA/EasyML/wiki/Tensorflow%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA%E5%8F%8A%E5%BA%94%E7%94%A8%E8%A7%84%E8%8C%83

**Comment by baitian77** [comment]
@sinllychen 
您好，看了《Quickstart》和《Tensorflow环境搭建及应用规范》，感觉更像是在docker中安装Tensorflow运行环境，然后手写Tensorflow代码。
想了解下，web页面拖拽的算子是否可指定为Tensorflow的算子，而非Spark mlib里的。谢谢。

**Comment by sinllychen** [comment]
@baitian77 您好，目前单机的tensorflow是这样的，分布式的tensorflow算子我们有提供脚本的支持。web页面的算子在深度学习这个目录下有提供CNN的tensorflow算子。其余算子不是tensorflow开发的。我们能够支持用户自己上传开发好的tensorflow算子
