### ISSUE TITLE
任务提交失败

### ISSUE THREAD

**Issue by xiangguanlan** [ICT-BDA/EasyML#66]
在docker镜像里，通过start-oozie.sh上传模型到HDFS，发现路径是/EML/Modules/模型名/*，而数据库镜像里，init-sql.sh脚本里，模型的路径为/EML/Modules/CEF4304E-13A5-4AEB-9E27-9A55A44D4657/*，二者不一致。请问，这是否是导致job失败的原因。

**Comment by sinllychen** [comment]
@xiangguanlan 您好，是的。你用的EML zip包用的是哪个版本呢。我们之前路径是/EML/Modules/模型名后来版本已经改成了/EML/Modules/CEF4304E-13A5-4AEB-9E27-9A55A44D4657/这种了。

**Comment by xiangguanlan** [comment]
用的是12的版本

**Comment by xiangguanlan** [comment]
版本确实用错了，参照[https://blog.csdn.net/lihuinihao/article/details/73188848](url)该博客，连接的镜像文件为EML.zip，为旧版本。建议删去该镜像，只保留新地址的各个版本镜像，防止有人看到博客导致下错版本。谢谢回复
