### ISSUE TITLE
python算法模型示例

### ISSUE THREAD

**Issue by xiangguanlan** [ICT-BDA/EasyML#67]
scala和java基础较差......，能否提供一个python编写算法模型的demo以供参考？包括接口要求和打包方式

**Comment by sinllychen** [comment]
@xiangguanlan 您好，请参考https://github.com/ICT-BDA/EasyML/wiki/Simple-Examples-of-EasyML。 这个虽然是java的例子，但是思路是一样的。

![image](https://user-images.githubusercontent.com/7518364/41087210-a2e94aa2-6a6e-11e8-8bb8-0a7477b2a6b8.png) 

 这个CMD 换成python  ***.py  就好了。然后参数需要在python文件里面留出来
