### ISSUE TITLE
IDEA启动的EML无法登陆

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#68]
![image](https://user-images.githubusercontent.com/25865085/41406344-b4f2a9a6-6ffe-11e8-8c23-980d26df0a09.png)

**Comment by sinllychen** [comment]
@powerLeePlus 您好，需要您那边验证一下mysql是否能够和您本机连通

**Comment by powerLeePlus** [comment]
@sinllychen 我自己改了mysql端口。可以了。谢谢
