### ISSUE TITLE
怎么通过项目中的i18n切换成中文

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#69]
@sinllychen 怎么通过项目中的i18n切换成中文。

**Comment by sinllychen** [comment]
@powerLeePlus 参考上面的URL，具体如下：
![image](https://user-images.githubusercontent.com/7518364/41957085-5ef65812-7a18-11e8-9e6b-694677897445.png)

**Comment by powerLeePlus** [comment]
@sinllychen locale=cn 线上这样是可以的。但是开源的代码在IDEA运行这个是没有效果的

**Comment by sinllychen** [comment]
@powerLeePlus 好的，这个我们具体看下，多谢反馈~
