### ISSUE TITLE
上传程序是通用算法，还是必须本平台指定的规则的算法

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#70]
@sinllychen 
可以上传的程序是跨平台的通用算法程序，还是必须本平台指定的规则的算法。
如果必须按照eml规定的规则，那这个算法程序的编写规则有吗，有没有相应的示例。
是需要特定语言实现算法程序吗。如果是都支持哪些语言。java?python?scala？......有示例吗？
十分感谢！！！

**Comment by sinllychen** [comment]
@powerLeePlus 您好，平台支持python、scala、java、shell等能够通过shell命令执行代码包的语言。算法的规范其实只是留出一些参数用于输入和输出以及用户输入参数。输入输出数据是通过文件的形式存在的。具体的示例可以参考 [代码示例](https://github.com/ICT-BDA/EasyML/wiki/Simple-Examples-of-EasyML)
