### ISSUE TITLE
Programable和Determinacy这两个能给具体介绍下吗

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#71]
上传程序时Programable和Determinacy这两个选项能给具体介绍下吗。

**Comment by sinllychen** [comment]
@powerLeePlus  您好。Programable 为可编程脚本的组件标识。支持python和shell可编程脚本。 用户可在组件上添加python、shell脚本。如下图：

![image](https://user-images.githubusercontent.com/7518364/41956928-e8eab636-7a17-11e8-92bb-24148beda9f8.png)

具体示例可以参考我们线上系统Demo：【实例】Titanic Demo

**Comment by sinllychen** [comment]
@powerLeePlus  Determinacy这个类型目前在系统中没有体现，可认为是废弃的。

**Comment by powerLeePlus** [comment]
@sinllychen 
1、也就是说上传程序时，即使不上传zip包，在创建任务时，写好script。这个任务也是可以正常执行的？
2、那zip程序包还会执行吗？
3、如果zip包也执行，那zip包执行和script执行顺序是啥呢

十分感谢耐心解答

**Comment by sinllychen** [comment]
@powerLeePlus 
1、上传的时候目前是没有针对这种类型进行过滤。所以还是要求要上传zip包。只是这个zip包对程序运行不起作用。命令行的配置上如下图：
![image](https://user-images.githubusercontent.com/7518364/41959794-97ec5c40-7a20-11e8-88f2-4fcd863b8e5c.png)
2、zip包不执行，仅执行脚本。这个脚本在运行过程中会上传到hdfs给yarn进行运行。

**Comment by powerLeePlus** [comment]
非常感谢！！！
