### ISSUE TITLE
注册验证邮箱链接跳转页面是空的

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#73]
点击邮箱中该链接：
![_20180629102512](https://user-images.githubusercontent.com/25865085/42069982-14bb12ea-7b87-11e8-89b8-50bbe2beea95.png)

页面是空的:
![image](https://user-images.githubusercontent.com/25865085/42070033-404e50f2-7b87-11e8-9390-9381f9597880.png)

**Comment by sinllychen** [comment]
@powerLeePlus 您好，这里面应该有个bug。我这边改下。开源这边没改了。之前我们自己内部的版本已经发现这个问题了。
