### ISSUE TITLE
IDEA下运行项目，为什么局域网内其他电脑无法访问。我防火墙都关了。

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#75]
使用http://127.0.0.1:8888/EMLStudio.html我自己电脑访问是可以的。
但是使用http://IP:8888/EMLStudio.html，不管是我自己电脑访问还是局域网其他电脑访问。都访问不了。
我防火区已经关了啊。win10

**Comment by SallyWY** [comment]
@powerLeePlus 由于127.0.0.1是localhost地址，所以直接输入http://ip是无法访问的。
输入http://localhost应该是可以正常访问的

**Comment by sinllychen** [comment]
@powerLeePlus 这个很正常啊，IDE只是提供了临时的部署环境。你需要让别的电脑也能访问，需要将工程打包，部署到tomcat或者别的类似的容器里面，然后保证你的电脑别的网段能访问
