### ISSUE TITLE
如何扩展算法（program data)

### ISSUE THREAD

**Issue by xzGithu** [ICT-BDA/EasyML#78]
你好，如何在本地部署的系统上扩展apriori和fp-growth这类算法呢？
 还请指点下，多谢

**Comment by sinllychen** [comment]
@xzGithu  您好，系统上的算法和平台是松耦合的，通过上传zip包（可以是jar包或者python脚本等能通过shell执行的包）的形式进行，具体请参考https://github.com/ICT-BDA/EasyML/wiki/Simple-Examples-of-EasyML  以及 https://github.com/ICT-BDA/EasyML/wiki/EasyML-User's-Guide  中的上传算子部分

**Comment by xzGithu** [comment]
@sinllychen 好的  多谢了 我测试一下试试

**Comment by xzGithu** [comment]
@sinllychen  
![image](https://user-images.githubusercontent.com/24711679/43942252-cb5be838-9ca9-11e8-9cbe-ef31eb9a16a9.png)
您好 上传算法包的时候总是有个500的错误 ，一上午upload program成功了一次 ，上传data时就很正常，hadooplog中也没有什么报错，请问这个要从那里排查呢，

**Comment by xzGithu** [comment]
@sinllychen 
![err](https://user-images.githubusercontent.com/24711679/43948668-0169adde-9cbe-11e8-98fe-3e93387f0b95.png)
![image](https://user-images.githubusercontent.com/24711679/43948693-13ac4434-9cbe-11e8-929b-933d164c0104.png)
您好，这个上传program是有内容校验的过程吗，我上传一个读文件的py脚本总是出现500的错误，把zip文件换成一个exe程序都能upload成功，这几行代码的是有什么问题呢还请指点下 。
之前写了个apriori的算法脚本带有--input的参数的可以正确的上传，也能运行。

**Comment by sinllychen** [comment]
@xzGithu  您这个用的是自己搭建的EasyML吗？程序本身没有内容校验，感觉您这个是hadoop hdfs同您部署的EasyML联通性有问题。

**Comment by sinllychen** [comment]
@xzGithu 具体可以看下tomcat的日志

**Comment by xzGithu** [comment]
@sinllychen ，您好，我这个是用docker在本地搭建的。
![image](https://user-images.githubusercontent.com/24711679/43952285-0d9342fa-9cc8-11e8-9e4f-18974adc619d.png)
这是在上传program时候的tomcat的log ，dfs中是创建了目录但是下面只有一个run.sh，没有我的zip和lib目录。

**Comment by xzGithu** [comment]
@sinllychen 我试了下往那个外网的eml上传也是上面500的错误

**Comment by xzGithu** [comment]
@sinllychen 这里又上传不了图片了，我发到了你的163的邮箱了，抱歉啊

**Comment by xzGithu** [comment]
@sinllychen 找到问题了， 脚本文件要被包含在目录里面再打包成zip。

**Comment by sinllychen** [comment]
@xzGithu 对的，是要包含在一个目录里面再进行打包。您之前说的exe文件也能够上传，这个不行吧？

**Comment by xzGithu** [comment]
@sinllychen 
FastStoneCapturecn/
├── FastStoneCapturePortable
│?? ├── FSCapture_en.exe
│?? ├── FSCapture.exe
│?? ├── FSCaptureHelp.chm
│?? ├── fsc.db
│?? ├── FSCrossHair_en.exe
│?? ├── FSCrossHair.exe
│?? ├── FSLogo.png
│?? ├── fsrec.db
│?? ├── FSRecorder_en.exe
│?? ├── FSRecorder.exe
│?? ├── LicenseAgreement.txt
│?? └── Portable.db
├── \306\301\304
302\324\330\325\276.url└── \312\271\323\303\270\374\320\302\313\265\303\367.txt
上面这种的目录结构，里面好多exe文件，在hdfs也能看到

/EML/Modules/D527584E-93DA-47BB-8FA2-F04A169CC9B9/lib/FastStoneCapturePortable
Permission	Owner	Group	Size	Last Modified	Replication	Block Size	Name
-rw-r--r--	root	supergroup	1.09 MB	2018/8/14 上午9:14:45	3	128 MB	FSCapture.exe
-rw-r--r--	root	supergroup	122.36 KB	2018/8/14 上午9:14:45	3	128 MB	FSCaptureHelp.chm
-rw-r--r--	root	supergroup	1.21 MB	2018/8/14 上午9:14:45	3	128 MB	FSCapture_en.exe
-rw-r--r--	root	supergroup	158 KB	2018/8/14 上午9:14:45	3	128 MB	FSCrossHair.exe
-rw-r--r--	root	supergroup	166.5 KB	2018/8/14 上午9:14:45	3	128 MB	FSCrossHair_en.exe

**Comment by xzGithu** [comment]
@sinllychen 您好，还有个问题请指点下吧，多谢了
我在做output结果到文件的时候 总是出现下面的问题，这个目录是hdfs上自己创建的为什么说没有呢，这个是要在哪里设置绝对路径吗
“Traceback (most recent call last):
  File "testmysql.py", line 16, in <module>
    with open(model_path+'/ouput', 'w') as f:
IOError: [Errno 2] No such file or directory: '2A976FEA-EB8C-4ED9-879C-1DEF94392359/ouput'
mv: cannot stat '2A976FEA-EB8C-4ED9-879C-1DEF94392359': No such file or directory”

**Comment by sinllychen** [comment]
@xzGithu  哦哦，看到了。上述那种方式，都放在一个文件夹里面，我们没有对文件进行校验。所以exe也能够上传。

**Comment by sinllychen** [comment]
@xzGithu 您好。您在设置这个算子的输出类型的时候，是否选择了Directory类型呢？如果选择了Directory的话，是可以帮你创建目录的，如果选的不是Directory，那么传过来的这个model_path就只是单独的文件而已。需要您自己去创建目录

**Comment by xzGithu** [comment]
@sinllychen  我的状况是那个oozie中appid的目录可以创建，但是那个output参数是不是应该在hdfs中输出一个与我的model_path名字一样的文件呢？现在这个文件不能生成。
![image](https://user-images.githubusercontent.com/24711679/44139100-aaba96f8-a0a8-11e8-92cc-f93ef1d4ebec.png)

**Comment by xzGithu** [comment]
@sinllychen 多谢啦，我这边可以了，类型还是选的general
