### ISSUE TITLE
非常棒的工具，但是试用过程中有几个疑问

### ISSUE THREAD

**Issue by zzbjpc** [ICT-BDA/EasyML#8]
- 是否可以自己上传非Java based模型（e.g. 用tensorflow导出的rnn）？我看Readme中有一个upload program的截图，截图中的那个模型是一个jar包么？

- 我用IDEA打开edit configuration的时候，并没有看到GWT Configuration，回到步骤2，步骤2中也没什么需要做的（我已经执行了maven clean&compile并且External libraries中和截图显示的一样），按照quick start无法正常启动，所以是不是配置GWT还有一些坑？

**Comment by sinllychen** [comment]
@zzbjpc  Hi，您好。首先非常感谢您的关注！

1、目前系统里面可支持能够用shell命令执行的模型，如Java，shell脚本语言开发的模型等，后续我们会将可编程节点（支持Python语言，已开发完成未合并），Tensorflow（目前正在开发调试中）运行环境集成到系统中。Upload program 可提供用户上传的是一个程序zip包，里面可以使Jar包或别的能够通过shell命令执行的程序。

2、项目本身的依赖包是maven依赖的，可以自动下载；项目的运行所依赖的集群等环境需要您自己去搭建，目前我们提供docker虚拟机的集群环境搭建方式，具体可参照https://github.com/ICT-BDA/EasyML/blob/master/QuickStart.md ，如果您是windows环境，可以自己下载windows 的docker 按照我们提供的步骤来搭建相应的运行环境，但是对自身电脑要求较高，可能会比较卡。

3、IDEA 我记得我当时用的时候直接就能跑的，不确定是不是版本问题，我用的是IDEA 15.0.3 教育版。现在我用的比较多的是eclipse， 您可以用eclipse导入maven工程试下，eclipse需要安装GWT插件。

**Comment by zzbjpc** [comment]
@sinllychen thanks~我再看看

**Comment by czs0x55aa** [comment]
@zzbjpc  我一开始用社区办的IDEA也是没有GWT Configuration，后来换成Ultimate版的就可以了

**Comment by hello-ming** [comment]
请问以下两个依赖包在哪里能找到？

<dependency>
    <groupId>eml</groupId>
    <artifactId>uploader</artifactId>
    <version>1.1.0</version>
</dependency>
<dependency>
    <groupId>eml</groupId>
    <artifactId>gwt-links</artifactId>
    <version>1.3</version>
</dependency

**Comment by sinllychen** [comment]
@hello-ming 您好，这两个包在https://github.com/ICT-BDA/EasyML/tree/master/lib/eml这个里面，因为在maven repository仓库里面没有这几个包，所以我们通过手动配置pom.xml将这几个包加入到本地仓库中。这几个包在maven编译完之后会自动加入到本地仓库的。

**Comment by hello-ming** [comment]
直接将lib/eml目录复制到本地仓库就可以，pom找不到的警告可以忽略。

**Comment by sinllychen** [comment]
@hello-ming  直接复制到本地仓库也行，但当初我们的初衷是不用自己手动添加到本地仓库，而是系统在maven编译的时候，自动将其拷贝到本地仓库。
