### ISSUE TITLE
JOB_TRACKER配置的是什么服务

### ISSUE THREAD

**Issue by powerLeePlus** [ICT-BDA/EasyML#86]
@sinllychen 
按说JOB_TRACKER是mapreduce的东西。但是看EML架构又是支持MapRudece2(Yarn)的。那到底是这个JOB_TRACKER配置的是什么：
![image](https://user-images.githubusercontent.com/25865085/47775329-4a513100-dd2a-11e8-940b-415f77d8afce.png)

**Comment by sinllychen** [comment]
@powerLeePlus 您好，这个参数是oozie需要的参数。oozie启动任务的时候是提交给yarn一个任务来进行启动的
