### ISSUE TITLE
用户注册失败

### ISSUE THREAD

**Issue by feiruyun** [ICT-BDA/EasyML#97]
Ubuntu系统下将平台搭建好了，在用户注册时提示“Verification email sent failed, please retry later”

**Comment by sinllychen** [comment]
@feiruyun 您好，注册的时候的邮件是调用了服务器的mail服务。需要修改工程文件中server-config.xml里面的MAIL_HOST、MAIL_USERNAME、MAIL_PASSWORD这几个参数

**Comment by feiruyun** [comment]
修改参数后，可以正常注册了，非常感谢！辛苦了
