### ISSUE TITLE
上传ETL文件出现[HTTP_ERROR]: Unsuccessful server response code of: 500

### ISSUE THREAD

**Issue by TangVVV** [ICT-BDA/EasyML#99]
在平台上下载了SqlETL，尝试重新上传，reader.jar文件已放入一个文件夹中打包成Zip格式，结果上传时出现Upload of file SqlETL.zip failed due to [HTTP_ERROR]: Unsuccessful server response code of: 500错误，请问如何解决

**Comment by sinllychen** [comment]
@TangVVV  您好，您需要先测试下系统是否能够正常上传数据。可以先测试下数据集的上传

**Comment by TangVVV** [comment]
好的谢谢！ @sinllychen
